#
# Module manifest for module 'Ravello'
#
# Generated by: Luc Dekens
#
# Generated on: 24-10-15
#

@{
  RootModule        = 'Ravello'
  ModuleVersion     = '1.1.3.0'
  GUID              = 'a5d6fd6d-ca99-4584-b519-0d203c03f361'
  Author            = 'Luc Dekens'
  Description       = 'Manages and automates the Ravello Systems environment'
  CompanyName       = 'Unknown'
  Copyright         = '(c) 2015 Luc Dekens. All rights reserved.'
  PowerShellVersion = '3.0'
  FunctionsToExport = '*-Ravello*'
  CmdletsToExport   = '*'
  VariablesToExport = 'Ravello*'
  AliasesToExport   = '*'
}

